<?php

// Language package:cn

return array(

    'ps_title' => 'Pousser',
    'ps_pinfo' => 'Informations',
    'ps_send' => 'Soumettre',

    // apis/exd_crawl.php
    'cw_crawl' => 'Cueillir',
    'cw_batch' => 'Nombre de bandes de données par lot',
    'cw_fskip' => 'Champ d `exclusion',
    'cw_urlfrom' => 'Extraire un site Web:',
    'cw_demodetail' => 'Page d `exemple',
    'cw_baselist' => 'Page de liste de base',
    'cw_pgsrule' => 'Règle de page',
    'cw_listdebug' => 'Page de liste',
    'cw_deetlist' => 'Site Web de la liste d `acquisition de débogage',
    'cw_donelog' => 'Enregistrement de page',
    'cw_getlistrule' => 'Extraire la liste des règles du site Web:',
    'cw_urlinc' => 'Site Web',
    'cw_urlnoi' => 'Site Web',
    'cw_urlrep' => 'Remplacement d `adresses Web',
    'cw_urlroot' => 'Table des matières',
    'cw_crlogs' => '[Enregistrement du site Web]',

    // apis/cron_plan.php
    'cr_addplan' => 'Tâches supplémentaires]',
    'cr_planord' => '[Planning task',
    'cr_addhook' => 'Tâche de crochet]',
    'cr_hookord' => '[Crochet task',
    'cr_kfine' => 'Key/Nom de fichier',
    'cr_cycle' => 'Intervalle',
    'cr_runprev' => 'Exécution antérieure',
    'cr_runnext' => 'Next Execution',
    'cr_runms' => 'Seconde d `exécution',
    'cr_dirun' => 'Exécution directe',
    'cr_odrun' => 'Programmation',
    'cr_tip1' => 'Nom de fichier correspondant à la tâche du plan<br>Sans.php',
    'cr_pname' => 'Task name',
    'cr_unit' => 'Unité',
    'cr_tip2' => 'Nombre: entre 1 et 120',
    'cr_last' => 'La dernière fois',
    'cr_tip3' => 'C `est le nombre de secondes dans une heure.',
    'hk_tip1' => 'Nom de fichier correspondant à la tâche du crochet<br>hook_Pas au début..php',

    // apis/seo_push.php
    'pu_cfok' => 'Le succès!',
    'pu_cfng' => 'Créer un échec',
    'pu_mapfile' => 'mapDocumentation',
    'pu_cv2' => 'Génération / affichage',
    'pu_create' => 'Générer',
    'pu_view' => 'Regarder',

    'pu_setv' => 'Valeur de réglage',
    'pu_ipush' => 'Propulsion',
    'pu_slink' => 'Présentation des liens',
    'pu_pfile' => 'Pousser un document',
    'pu_tip1' => '(Ou remplissez manuellement l `adresse dans la zone suivante)',
    'pu_plink' => 'Raccord de poussée',
    'pu_ldemo' => 'Référence de connexion',
    'pu_tip2' => 'Procédé de présentation de sitemap.Xml à des moteurs de recherche importants',
    
    'pu_mfname' => 'MapNom de fichier',
    'pu_modset' => 'Configuration de modèle',
    'pu_itpl' => 'itemModèle',
    'pu_ftpl' => 'fileModèle',
    'pu_idemo' => 'itemRéférences',
    'pu_hdemo' => 'htmlReference (File Model))',
    'pu_xdemo' => 'xmlReference (File Model))',
    'pu_fdemo' => 'fileRéférences',

    // apis/exd_share.php
    'sh_title' => 'Partage de données',
    'sh_json' => 'jsonPartager',
    'sh_tpl' => 'tplAppeler',
    'sh_tip1' => '(Coupez / ret / tpl)',
    'sh_tip2' => '(Paramètres d `affichage cut / ret / tpl)',
    'sh_cg' => 'Colonne / classe',
    'sh_whr' => 'Conditions de données',
    'sh_show' => 'Display set',
    'sh_mod' => 'Module de données',
    'sh_mode' => 'Mode d `appel',
    'sh_url' => 'Adresse d `appel',
    'sh_ctpl' => 'tplTranscodage',
    'sh_surl' => 'urlSignature',
    'sh_res' => 'Résultat de l `appel',

    // binc/exd_inc1.php
    'ei_cwraldata' => 'Acquisition de données',
    'ei_impdata' => 'Import de données',
    'ei_back' => 'Retour',
    'ei_paln' => 'Programmation',
    'ei_sharecfg' => 'Configuration partagée',
    'ei_cfgfile' => 'Fichier de configuration',
    'ei_editcfg' => 'Modifier la configuration',
    'ei_doc' => 'Document',
    'ei_tip2nd' => 'Second development: Data extension (System Tool))',
    'ei_fldxcfg' => 'Configuration des champs [[val]]]',
    'ei_name' => 'Titre du projet',
    'ei_demodetail' => 'Page d `exemple',
    'ei_debugrule' => 'Règle de débogage',
    'ei_opendemo' => 'Ouvrir la page de l `exemple',
    'ei_debfld' => 'Débogage des champs [[val]]]',
    'ei_getrule' => 'Extraction de règles de contenu original',
    'ei_fromdb' => 'Données de source',
    'ei_fromfield' => 'Champ source',
    'ei_resdea' => 'Traitement de contenu',
    'ei_reorg' => 'Remplacer le contenu original',
    'ei_cdeal' => 'Traitement intégré',
    'ei_retab' => 'Tableau de remplacement de contenu',
    'ei_param' => 'Paramètres',
    'ei_resfunc' => 'Résultat processing function',
    'ei_nuldef' => 'Par défaut spatio - temporel',
    'ei_extab' => 'Tableau',
    'ei_db' => 'Base de données',
    'ei_nowval' => 'Valeur actuelle',
    'ei_maxlen' => 'Input Max \ \ 124g Database length',
    'ei_nchr' => 'Nombre de caractères',
    'ei_skipfld' => 'Champ de sortie',
    'ei_fldcfg' => 'Configuration de champ',
    'ei_addfld' => 'Champ supplémentaire',

    // apis/exd_psyn.php
    'sy_add' => 'Synchronisation de données]',
    'sy_plan' => '[Synchronisation de données',
    'sy_apiurl' => 'apiAdresse',
    'sy_tipapi' => 'Sans objet en français: [/ index.Php? Ajax - XDB]',
    'sy_limit' => 'Nombre de bandes de données par lot',
    'sy_type' => 'Catégorie',
    'sy_tipnul' => 'Vide ou illimité',
    'sy_tlog' => 'Enregistrement de données',

    // apis/exd_oimp.php
    'oi_from' => 'Source',
    'oi_logs' => 'Enregistrement',
    'oi_imp' => 'Importer',
    'oi_copy' => 'Programme de reproduction',
    'oi_fdb' => 'Données de source',
    'oi_fsql' => 'SourceSQL',
    'oi_int' => 'Forme',
    'oi_chr' => 'Caractères',
    'oi_kfield' => 'Champ de touche principale',
    'oi_tfield' => 'Champ de temps',
    'oi_limit' => 'Nombre de bandes de données par lot',
    'oi_skip' => 'Champ d `exclusion',
    'oi_tlog' => 'Enregistrement de données',

    // apis/exd*
    'exd_reurl' => 'Notes / notes de configuration / extraits du site Web:',
    'exd_rutip' => "Pour plus de détails, voir Documents:", 
    'exd_skdef' => 'Exclure les champs / valeurs par défaut: une ligne; format par défaut \n:',
    'exd_imtip' => "Source SQL: la table principale est fixée à m; n exclusion champs / valeurs par défaut: une ligne; et",
    'exd_iline' => 'Un par un.',

    // apis/jifen_plan.php
    'jf_updcfg' => 'Update configuration',
    'jf_upd' => 'Update',
    'jf_add' => 'Augmentation',
    'jf_jfcnt' => 'Integral Number',
    'jf_jifen' => 'Integration',
    'jf_logs' => 'Integral record',
    'jf_jfcnt2' => 'Quantité intégrale',
    'jf_l19n' => 'Permission 1 - 9',

    // apis/sms_send.php
    'ss_title' => 'SMS',
    'ss_web' => 'Web',
    'ss_apib' => 'Solde d `interface',
    'ss_close' => 'Interface désactivée ou désactivée!',
    'ss_tel' => 'Numéro de téléphone',
    'ss_msg' => 'SMS',
    'ss_tip0' => '(Le solde est zéro, pas d `envoi.)',
    'ss_send' => 'Envoyer',
    'ss_cnta' => 'Input',
    'ss_cntb' => 'Caractères',
    'ss_set' => 'Set',
    'ss_tips' => 'Annotations',
    'ss_tipc' => 'Numéro un par ligne, ou utiliser, pour séparer; contenu dans 240 mots',
    'ss_balance' => 'Solde',

    // apis/pay_logs.php
    'pay_amount' => 'Montant',
    'pay_api' => 'InterfaceID',
    'pay_method' => 'Méthode',
    'pay_dir' => 'Table des matières',
    'pay_note' => 'Note',
    'pay_cfg' => 'Configuration',
    'pay_pcfg' => 'Configuration des paiements',
    'pay_2ndoc' => 'Second Development Document',

    // apis/*
    'exp_set' => 'Set',
    'exp_detail' => 'Détails',
    'sms_count' => 'Quantité',
    'ord_icon' => 'Icône',
    'ord_icocss' => 'Nom de fichier d `icônecss',
    'ord_extfee' => 'Montant supplémentaire',
    'qa_alltype' => 'Toutes catégories',
    'qa_alltag' => 'Toutes les étiquettes',
    'qa_reset' => 'Mise à jour / remplacement',
    'cfg_tips' => 'Avertissement',     // acfgs
    'cfg_nocfg' => 'Pas de configuration',
    'cfg_copy' => 'Veuillez copier le fichier',
    'cfg_to' => ' Pour ',
    'cfg_editip' => 'Et modifier les paramètres pour terminer la configuration',
    'cfg_nowcfg' => 'Configuration actuelle',
    'cfg_nowfile' => 'Fichier de configuration actuel',
    'cfg_edit' => 'Modifier la configuration',
    'cfg_optime' => 'Temps de fonctionnement',

    // dops/dopComs.php
    'dc_c1024' => '10-24Caractères',
    'dc_norel' => 'Sans module de corrélation]ID',
    // glib/fldCfgs.php
    'fc_rftype' => 'Catégorie de référence',
    'fc_rffield' => 'Champ de référence',

    //dops/dopCheck.php
    'ck_grade' => '[val]!',
    'ck_stop' => '[val]!',
    'ck_login' => 'Aucun droit d `action, s` il vous plaît.',
    'ck_all' => 'Dépassement de la limite de publication',
    'ck_day' => 'Au - delà de la limite de publication, article [[val]]!',
    'ck_rep' => 'Limite de temps de publication répétée,<br>L `intervalle de temps doit être >',

    'tip_slogs' => 'Pour optimiser et personnaliser les paramètres',
    'tip_ssel' => 'Il faut choisir.',
    'tip_suser' => 'Pour modifier les paramètres de l `opérateur',
    'tip_sip' => 'Pour modifier les paramètres IP de l `opérateur',

    //flow/dops/xxx
    'dops_parerr' => 'Erreur paramétrique',
    'dops_add' => 'Augmentation',
    'dops_edit' => 'Modifier',
    'dops_ok' => 'Succès!',
    'dops_okn' => 'Record (VAL)!',
    'dops_add2' => 'Informations supplémentaires',
    'dops_adm2' => 'Gestion',

    'dops_checked' => 'Audit',
    'dops_hide' => 'Cacher',
    'dops_del' => 'Delete',

    'dops_setop' => 'Sélectionnez l `opération!',
    'dops_setitem' => 'Veuillez cocher l `enregistrement de l` opération!',
    'dops_send' => 'Soumettre',
    'dops_back' => 'Retour',
    'dops_nodata' => 'Rien!',
    'dops_opok' => 'Opération réussie!',

    'dops_clearok' => 'Nettoyage réussi!',
    'dops_clear' => 'Nettoyage',
    'dops_search' => 'Rechercher',

    'dops_icat' => 'Colonne',
    'dops_ishow' => 'Display',
    'dops_copy' => 'Copier',
    'dops_cpro' => 'Produit de reproduction',
    'dops_rem' => 'Observations',

    'dops_delok' => 'Delete Record',
    'dops_kid' => 'Identification',
    'dops_itemname' => 'Nom de l `entrée',
    'dops_cpok' => 'Copie réussie!',
    'dops_detail' => 'Détails',
    'dops_exeu' => 'Mise en œuvre',

    'dops_fromdata' => 'Source',
    'dops_reldata' => 'Associative information',
    'dops_orduidd' => 'Numéro de compte)',
    'dops_orduida' => 'Numéro de compte)',
    'dops_ordkidd' => 'ID(Descendre)',
    'dops_ordkida' => 'ID(Litre)',
    'dops_ordtimd' => 'Temps supplémentaire)',
    'dops_ordtima' => 'Heure d `ajout)',
    'dops_ordasc' => '(Litre)',
    'dops_orddesc' => '(Descendre)',

    'log_aip' => 'AjouterIP',
    'log_eip' => 'ModifierIP',
    'log_atime' => 'Temps supplémentaire',
    'log_etime' => 'Temps de modification',

    'log_optime' => 'Temps de fonctionnement',
    'log_opuser' => 'Opérateur',
    'log_opip' => 'ManipulerIP',
    'log_opadd' => 'Ajouter:',
    'log_opedit' => 'Modifier:',

    'op0_filt' => '-Filtrage-',
    'op0_search' => '-Rechercher-',
    'op0_bacth' => '-Opération de masse-',
    'op0_order' => '-Tri-',    
    'op0_show' => '-Display-',
    'op0_cat' => '-Colonnes-',
    'op0_type' => '-Catégorie-',
    'op0_field' => '-Champ-',
    'op0_area' => '-Champ d `application-',

    'op_op4' => "upd|更新\ndel|删除\nshow|启用\nstop|禁用",
    'op_upd' => 'Update', 
    'op_del' => 'Delete',
    'op_open' => 'Activer',
    'op_close' => 'Interdire',
    'op_op3' => "del|删除\nshow|显示\nhidden|隐藏",
    'op_show' => 'Display', 
    'op_hide' => 'Cacher',
    'op_delsel' => 'Supprimer la sélection',
    'op_delnow' => 'Supprimer',

    'title_select' => 'Choix',
    'title_name' => 'Nom',
    'title_top' => 'Tri',
    'title_enable' => 'Activer',
    'title_char' => 'Alphabet',
    'title_level' => 'Grade',
    'title_frame' => 'Structure',
    'title_subtype' => 'Sous - projet',
    'title_param' => 'Paramètres',
    'title_edit' => 'Modifier',
    'title_note' => 'Notes',
    'title_model' => 'Modèle',
    'title_type' => 'Type',
    'title_defval' => 'Valeur par défaut',
    'title_cfg' => 'Configuration',

    'title_perm' => 'Compétence',
    'title_field' => 'Champ',
    'title_fields' => 'Champ',
    'title_set' => 'Set',
    'title_copy' => 'Copier',
    'title_cata' => 'Colonnes',
    'title_bei' => 'Rechange',
    'title_grade' => 'Grade',
    'title_mode' => 'Mode',
    'title_admin' => 'Gestion',
    'title_parset' => 'Paramètres',

    'title_op' => 'Manipuler',
    'title_pid' => 'Article parent',
    'title_newid' => 'NouveauID',
    'title_attrset' => 'Attributs',
    'title_attrtitle' => 'Attribut',

    'msg_pkitem' => 'Veuillez cocher l `élément d` opération!',
    'msg_set' => 'Ça marche!',
    'msg_upd' => 'Mise à jour réussie!',
    'msg_add' => 'Ajouter le succès!',
    'msg_del' => 'Delete',
    'msg_move' => 'Mouvement réussi',
    'msg_exists' => '[val]) est occupée!',
    'msg_delxng' => 'Delete Failure',
    'msg_delxok' => 'Conditions actuelles: [[val]] supprimer le succès',

    'fl_addin' => 'Ajouter une entrée',
    'fl_addtitle' => 'Ajouter une entrée',
    'fl_opbatch' => 'Opération de masse',
    'fl_kflag' => 'KeyIdentification',
    'fl_cfgtab' => 'Configuration',
    'fl_cfgtip' => 'Format: touche = valeur, ligne par ligne;',
    'fl_deeltitle' => 'Exécution',

);
