<?php

// Paquete lingüístico:cn

return array(

    'ps_title' => 'Empujar vt.',
    'ps_pinfo' => 'Enviar información',
    'ps_send' => 'Presentación',

    // apis/exd_crawl.php
    'cw_crawl' => 'Recoger',
    'cw_batch' => 'Series de datos por serie',
    'cw_fskip' => 'Eliminar campo',
    'cw_urlfrom' => 'Extrayendo la página web:',
    'cw_demodetail' => 'Detalles del ejemplo',
    'cw_baselist' => 'Lista básica',
    'cw_pgsrule' => 'Regla de páginas',
    'cw_listdebug' => 'Lista de páginas',
    'cw_deetlist' => 'Lista de comprobación',
    'cw_donelog' => 'Registro de páginas tomadas',
    'cw_getlistrule' => 'Lista de direcciones:',
    'cw_urlinc' => 'Sitio web',
    'cw_urlnoi' => 'Página web',
    'cw_urlrep' => 'Página web',
    'cw_urlroot' => 'Directorio raíz',
    'cw_crlogs' => '[Sitio web]',

    // apis/cron_plan.php
    'cr_addplan' => 'Añadir[tareas previstas]]',
    'cr_planord' => '[Planificación de la Misión',
    'cr_addhook' => 'Añadir Misión garfio]',
    'cr_hookord' => '[Misión garfio.',
    'cr_kfine' => 'Key/Nombre del archivo',
    'cr_cycle' => 'Intervalo de tiempo',
    'cr_runprev' => 'Última vez',
    'cr_runnext' => 'Próxima vez',
    'cr_runms' => 'Minuto de ejecución',
    'cr_dirun' => 'Ejecución directa',
    'cr_odrun' => 'Ejecución de programas',
    'cr_tip1' => 'Nombre de archivo de la tarea prevista<br>No..php',
    'cr_pname' => 'Nombre de la tarea',
    'cr_unit' => 'Unidad',
    'cr_tip2' => 'Cifras:1 a 120',
    'cr_last' => 'última',
    'cr_tip3' => 'Es decir,el número de segundos en una hora.',
    'hk_tip1' => 'Nombre de archivo de la Misión garfio<br>hook_Al principio no..php',

    // apis/seo_push.php
    'pu_cfok' => '¡Formación exitosa!',
    'pu_cfng' => 'Formación fallida.',
    'pu_mapfile' => 'mapDocumentación',
    'pu_cv2' => 'Generar/ver',
    'pu_create' => 'Generación',
    'pu_view' => 'Ver',

    'pu_setv' => 'Establecer valor',
    'pu_ipush' => 'Entrega voluntaria',
    'pu_slink' => 'Enlace de enlace',
    'pu_pfile' => 'Empujar documento',
    'pu_tip1' => '(O a mano en los siguientes Recuadros)',
    'pu_plink' => 'Conexión de empuje',
    'pu_ldemo' => 'Referencia de conexión',
    'pu_tip2' => 'MÉTODO PARA LA PRESENTACIÓN DE sitemap.xml a los principales motores de bÃºsqueda',
    
    'pu_mfname' => 'MapNombre del archivo',
    'pu_modset' => 'Configuración del modelo',
    'pu_itpl' => 'itemPlantilla',
    'pu_ftpl' => 'filePlantilla',
    'pu_idemo' => 'itemReferencias',
    'pu_hdemo' => 'htmlReference(File MODEL))',
    'pu_xdemo' => 'xmlReference(File MODEL))',
    'pu_fdemo' => 'fileReferencias',

    // apis/exd_share.php
    'sh_title' => 'Intercambio de datos',
    'sh_json' => 'jsonCompartir',
    'sh_tpl' => 'tplLlamar',
    'sh_tip1' => '(Los parámetros son Cut/Ret/tpl.)',
    'sh_tip2' => '(Puede configurar los siguientes parámetros de visualización Cut/Ret/tpl)',
    'sh_cg' => 'Columna/nivel',
    'sh_whr' => 'Condiciones de datos',
    'sh_show' => 'Preferencias de visualización',
    'sh_mod' => 'Módulo de datos',
    'sh_mode' => 'Modo de llamada',
    'sh_url' => 'Dirección de llamadas',
    'sh_ctpl' => 'tplTransliterar',
    'sh_surl' => 'urlFirma',
    'sh_res' => 'Resultados de llamada',

    // binc/exd_inc1.php
    'ei_cwraldata' => 'Reunión de datos',
    'ei_impdata' => 'Importación de datos',
    'ei_back' => 'Regreso',
    'ei_paln' => 'Programación F.',
    'ei_sharecfg' => 'Configuración compartida',
    'ei_cfgfile' => 'Archivo de configuración',
    'ei_editcfg' => 'Modificar configuración',
    'ei_doc' => 'Documentación',
    'ei_tip2nd' => 'Desarrollo secundario:ampliación de los datos(herramienta del sistema))',
    'ei_fldxcfg' => 'Configuración del campo[{val}]',
    'ei_name' => 'Título del proyecto',
    'ei_demodetail' => 'Detalles del ejemplo',
    'ei_debugrule' => 'Reglas de ensayo',
    'ei_opendemo' => 'Abrir hoja de ejemplo',
    'ei_debfld' => 'Probando y recogiendo campos[{val}]',
    'ei_getrule' => 'Normas para extraer el contenido original',
    'ei_fromdb' => 'Datos de origen',
    'ei_fromfield' => 'Campo fuente',
    'ei_resdea' => 'Tratamiento del contenido',
    'ei_reorg' => 'Reemplazar el contenido original',
    'ei_cdeal' => 'Tratamiento integrado',
    'ei_retab' => 'Tabla de sustitución',
    'ei_param' => 'Parámetros',
    'ei_resfunc' => 'End Function',
    'ei_nuldef' => 'Valor predeterminado por defecto',
    'ei_extab' => 'Tabla de partición',
    'ei_db' => 'Base',
    'ei_nowval' => 'Valor actual',
    'ei_maxlen' => 'Introduzca la longitud máxima de la base de datos',
    'ei_nchr' => 'Número de caracteres',
    'ei_skipfld' => 'Campo de salida',
    'ei_fldcfg' => 'Configuración del campo',
    'ei_addfld' => 'Campo adicional',

    // apis/exd_psyn.php
    'sy_add' => 'Añadir[sincronización de datos]',
    'sy_plan' => '[Sincronización de datos',
    'sy_apiurl' => 'apiDirección',
    'sy_tipapi' => 'Sin incluir la parte posterior:[/index.php?Ajax-exdb]',
    'sy_limit' => 'Número de barras de datos síncronas por serie',
    'sy_type' => 'Categoría',
    'sy_tipnul' => 'O()o',
    'sy_tlog' => 'Registro de datos',

    // apis/exd_oimp.php
    'oi_from' => 'Fuente',
    'oi_logs' => 'Actas',
    'oi_imp' => 'Importar',
    'oi_copy' => 'Programa de reproducción',
    'oi_fdb' => 'Datos de origen',
    'oi_fsql' => 'FuenteSQL',
    'oi_int' => 'Deformación',
    'oi_chr' => 'Carácter',
    'oi_kfield' => 'Campo principal',
    'oi_tfield' => 'Campo de tiempo',
    'oi_limit' => 'Importación de datos por serie',
    'oi_skip' => 'Eliminar campo',
    'oi_tlog' => 'Entrada de datos',

    // apis/exd*
    'exd_reurl' => 'Observaciones/establecimiento de notas/extracción de sitios en la Web:',
    'exd_rutip' => "[Sustituir el sitio web]formato de valor predeterminado:oldval=newval-para más detalles véase el documento:", 
    'exd_skdef' => 'Excluir campos/valores predeterminados:una línea; un formato de valor predeterminado:',
    'exd_imtip' => "Fuente:SQL:la tabla maestra se fija como mi alias; exclusión de campos/valores por defecto:una línea; formato por defecto:nombre de campo=valor de campo-importación de datos de demostración:http://pan.baidu.com/share/home?UK=319197020-=odata`u demo.rar",
    'exd_iline' => 'Una línea.',

    // apis/jifen_plan.php
    'jf_updcfg' => 'Actualizar configuración',
    'jf_upd' => 'Actualización',
    'jf_add' => 'Adición',
    'jf_jfcnt' => 'Integral M.',
    'jf_jifen' => 'Integral',
    'jf_logs' => 'Registro integral',
    'jf_jfcnt2' => 'Cantidad integral',
    'jf_l19n' => 'Número permitido 1-9',

    // apis/sms_send.php
    'ss_title' => 'Enviar SMS',
    'ss_web' => 'Red',
    'ss_apib' => 'Saldo de interfaz',
    'ss_close' => 'Interfaz cerrada o inválida!',
    'ss_tel' => 'Número de teléfono',
    'ss_msg' => 'Contenido del mensaje',
    'ss_tip0' => '(El saldo es cero,no se puede enviar)',
    'ss_send' => 'Enviar',
    'ss_cnta' => 'Introducido.',
    'ss_cntb' => 'Carácter de caracteres',
    'ss_set' => 'Configuración',
    'ss_tips' => 'Nota explicativa',
    'ss_tipc' => 'Número uno en una línea,o con una,para separar; contenido en menos de 240 palabras',
    'ss_balance' => 'Saldo',

    // apis/pay_logs.php
    'pay_amount' => 'Importe',
    'pay_api' => 'InterfazID',
    'pay_method' => 'Metodología',
    'pay_dir' => 'Índice',
    'pay_note' => 'Nota',
    'pay_cfg' => 'Configuración',
    'pay_pcfg' => 'Configuración de pago',
    'pay_2ndoc' => 'Segundo desarrollo del documento.',

    // apis/*
    'exp_set' => 'Configuración',
    'exp_detail' => 'Información detallada',
    'sms_count' => 'Cantidad',
    'ord_icon' => 'Icono',
    'ord_icocss' => 'Archivo de iconocss',
    'ord_extfee' => 'Importe adicional',
    'qa_alltype' => 'Todas las categorías',
    'qa_alltag' => 'Todas las etiquetas',
    'qa_reset' => 'Renovación/sustitución',
    'cfg_tips' => 'Pista',     // acfgs
    'cfg_nocfg' => 'Configuración actual',
    'cfg_copy' => 'Copiar archivo',
    'cfg_to' => ' Por ',
    'cfg_editip' => 'Modificar parámetro completar configuración',
    'cfg_nowcfg' => 'Configuración actual',
    'cfg_nowfile' => 'Archivo de configuración actual',
    'cfg_edit' => 'Modificar configuración',
    'cfg_optime' => 'Tiempo de funcionamiento',

    // dops/dopComs.php
    'dc_c1024' => '10-24Carácter',
    'dc_norel' => 'No[módulo relacional]ID',
    // glib/fldCfgs.php
    'fc_rftype' => 'Categoría de referencia',
    'fc_rffield' => 'Campo de referencia',

    //dops/dopCheck.php
    'ck_grade' => 'Operación no autorizada[{val}]',
    'ck_stop' => 'Operación no autorizada[{val}]',
    'ck_login' => 'No tiene permiso de operación,por favor.',
    'ck_all' => 'Por encima del límite de emisión,la cantidad total publicada[artículo{val}]',
    'ck_day' => 'Cantidad atribuida por encima del límite de emisión,día IP[artículo{val}]',
    'ck_rep' => 'REPETICIÓN de los límites temporales<br>¡El intervalo de tiempo seráde{val}segundos!',

    'tip_slogs' => 'Para optimizar y personalizar las preferencias',
    'tip_ssel' => 'Hay que elegir.',
    'tip_suser' => 'Cambiar configuración del operador',
    'tip_sip' => 'Para modificar la configuración IP del operador',

    //flow/dops/xxx
    'dops_parerr' => 'Error de parámetro',
    'dops_add' => 'Adición',
    'dops_edit' => 'Modificación',
    'dops_ok' => '¡Éxito!',
    'dops_okn' => '¡El récord{val}triunfa!',
    'dops_add2' => 'Información adicional',
    'dops_adm2' => 'Gestión',

    'dops_checked' => 'Auditoría',
    'dops_hide' => 'Ocultar',
    'dops_del' => 'Eliminar',

    'dops_setop' => '¡Por favor,seleccione el proyecto operativo!',
    'dops_setitem' => '¡Marque el registro de operaciones!',
    'dops_send' => 'Presentación',
    'dops_back' => 'Regreso',
    'dops_nodata' => '¡Nada!',
    'dops_opok' => '¡Funcionó!',

    'dops_clearok' => '¡Limpieza exitosa!',
    'dops_clear' => 'Limpieza',
    'dops_search' => 'Búsqueda',

    'dops_icat' => 'Columna de ubicación',
    'dops_ishow' => 'Mostrar',
    'dops_copy' => 'Copiar',
    'dops_cpro' => 'Copiar producto',
    'dops_rem' => 'Observaciones',

    'dops_delok' => '¡Borrar archivos ha tenidoéxito!',
    'dops_kid' => 'Identificación',
    'dops_itemname' => 'Nombre de entrada',
    'dops_cpok' => '¡Copiado!',
    'dops_detail' => 'Información detallada',
    'dops_exeu' => 'Ejecución',

    'dops_fromdata' => 'Datos de origen',
    'dops_reldata' => 'Información relevante',
    'dops_orduidd' => 'Número de cuenta)',
    'dops_orduida' => 'Número de cuenta)',
    'dops_ordkidd' => 'ID(Bajar)',
    'dops_ordkida' => 'ID(Litro)',
    'dops_ordtimd' => 'Añadir tiempo(bajar))',
    'dops_ordtima' => 'Añadir tiempo(l))',
    'dops_ordasc' => '(Litro)',
    'dops_orddesc' => '(Bajar)',

    'log_aip' => 'AdiciónIP',
    'log_eip' => 'ModificaciónIP',
    'log_atime' => 'Añadir tiempo',
    'log_etime' => 'Tiempo de modificación',

    'log_optime' => 'Tiempo de funcionamiento',
    'log_opuser' => 'Operador',
    'log_opip' => 'OperaciónIP',
    'log_opadd' => 'Adición:',
    'log_opedit' => 'Modificación:',

    'op0_filt' => '-Filtrar-',
    'op0_search' => '-Búsqueda-',
    'op0_bacth' => '-Operaciones de volumen-',
    'op0_order' => '-Ordenar-',    
    'op0_show' => '-Mostrar-',
    'op0_cat' => '-Columna-',
    'op0_type' => '-Categoría-',
    'op0_field' => '-Campo-',
    'op0_area' => '-Alcance-',

    'op_op4' => "upd|Actualizar 12423 borrar cómo funciona el sistema de discoóptico desactivado",
    'op_upd' => 'Actualización',
    'op_del' => 'Eliminar',
    'op_open' => 'Activar',
    'op_close' => 'Desactivar',
    'op_op3' => "del|Borra el visor de las 1240s.Esconde el velo.",
    'op_show' => 'Mostrar',
    'op_hide' => 'Ocultar',
    'op_delsel' => 'Borrar la selección',
    'op_delnow' => 'Eliminar el presente',

    'title_select' => 'Elección',
    'title_name' => 'Nombre',
    'title_top' => 'Ordenar',
    'title_enable' => 'Activar',
    'title_char' => 'Alfabeto',
    'title_level' => 'Nivel',
    'title_frame' => 'Estructura',
    'title_subtype' => 'Subproyectos:',
    'title_param' => 'Parámetros',
    'title_edit' => 'Modificación',
    'title_note' => 'Observaciones',
    'title_model' => 'Modelo',
    'title_type' => 'Tipo',
    'title_defval' => 'Valor predeterminado',
    'title_cfg' => 'Configuración',

    'title_perm' => 'Competencia',
    'title_field' => 'Campo',
    'title_fields' => 'Campo',
    'title_set' => 'Configuración',
    'title_copy' => 'Copiar',
    'title_cata' => 'Columna',
    'title_bei' => 'Reserva',
    'title_grade' => 'Grado',
    'title_mode' => 'Patrón',
    'title_admin' => 'Gestión',
    'title_parset' => 'Preferencias de parámetro',

    'title_op' => 'Operación',
    'title_pid' => 'Entrada del padre',
    'title_newid' => 'NuevoID',
    'title_attrset' => 'Configuración de atributo',
    'title_attrtitle' => 'Atributo',

    'msg_pkitem' => '¡Marque la casilla de operaciones,por favor!',
    'msg_set' => '¡Listo!',
    'msg_upd' => '¡Renovación exitosa!',
    'msg_add' => '¡Añadiréxito!',
    'msg_del' => '¡Borraréxito!',
    'msg_move' => 'Mover conéxito',
    'msg_exists' => '¡La entrada[{val}]Estáocupada!',
    'msg_delxng' => 'Error al borrar.Establezca las condiciones.',
    'msg_delxok' => 'Condiciones actuales:[valor}]suprimido conéxito',

    'fl_addin' => 'Añadir entrada-en',
    'fl_addtitle' => 'Añadir entrada',
    'fl_opbatch' => 'Operaciones de volumen',
    'fl_kflag' => 'KeyIdentificación',
    'fl_cfgtab' => 'Configuración del Grupo',
    'fl_cfgtip' => 'Formato:clave=valor,línea por línea;',
    'fl_deeltitle' => 'Operación de ejecución',

);
